meta_product_name: "Karma-Connect"
meta_title: "Karma-Connect- Better together"
meta_description: "Helping out one another by connecting, you are not alone anymore"
meta_image: "front-image.jpg" # should exist in `app/assets/images/`
   # required for Twitter Cards
